### ISSUE TITLE
Add AVAX as a payment option

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/eth-payment-processor#27]
### Scenario:
`eth-payment-processor` for EXR projects currently allows payment in aBLOCK, aaBLOCK and ETH but *not* AVAX.

An AVAX address is generated but AVAX doesn't show in the list of accepted tokens. eg:

```  context = {
        'result': {
            'project_id': project_name,
            'api_key': api_key,
            'payment_eth_address': eth_address,
            'payment_avax_address': avax_address,
            'payment_amount_tier1_eth': tier1_expected_amount,
            'payment_amount_tier2_eth': tier2_expected_amount,
            'payment_amount_tier1_ablock': tier1_expected_amount_ablock,
            'payment_amount_tier2_ablock': tier2_expected_amount_ablock,
            'payment_amount_tier1_aablock': tier1_expected_amount_aablock,
            'payment_amount_tier2_aablock': tier2_expected_amount_aablock,
            'expiry_time': payment_expires.strftime("%Y-%m-%d %H:%M:%S EST")
        }
```
### To do:
- [ ] add AVAX as an accepted payment currency for `exr projects`
- [ ] add required options for AVAX fee values to the `auto-builder`

### QA:
- [ ] snode op can set the AVAX payment values for tier 1
- [ ] the relevant project fee is shown in AVAX
- [ ] the user is able to pay for a project with AVAX

**Comment by sh-rn** [comment]
@ConanMishler ok to close this now?

**Comment by ConanMishler** [comment]
Yeah, I listed this issue as one that would be closed when https://github.com/blocknetdx/eth-payment-processor/pull/35 was merged, but it looks like the auto-closing feature of Github didn't work on this one. Closing now.
