### ISSUE TITLE
remove unwanted 3rd party conns

### ISSUE THREAD

**Issue by pom11** [blocknetdx/eth-payment-processor#8]

**Comment by shrnkld** [comment]
Please remove ref to Coinbase from logging info: 

``` last_amount_update_time_eth = int(time.time())
     except Exception as e:
         logging.info('coinbase eth price lookup failed with error: {}'.format(e))```

**Comment by ConanMishler** [comment]
Sorry for moving this issue between the columns so much! I finally decided to leave it in the `In Progress` column because there is still a chance the word, "coinbase" can get written to the logs. Therefore, the task isn't complete.

**Comment by pom11** [comment]
where are the occurences of "coinbase"? i thought i removed them all
