### ISSUE TITLE
Add CI to eth-payment-processor repo

### ISSUE THREAD

**Issue by leonVrashitov** [blocknetdx/eth-payment-processor#9]
1) Build image
2) Push image to dockerhub

**Comment by ConanMishler** [comment]
Hmm... I don't seem to have permission to assign this task to someone, but I agree with shorn: let's assign this task to @pom11. He should be able to copy/paste much of the CI code from the `dockerimages` repo, I'd think.

**Comment by shrnkld** [comment]
@pom11 @ConanMishler can you let me know if this is still relevant please

**Comment by pom11** [comment]
it is. after aablock testing will sove this
